<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGakbhyy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGakbhyy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGakbhyy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGakbhyy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGakbhyy\appProdProjectContainer([
    'container.build_hash' => 'Gakbhyy',
    'container.build_id' => '1078a27f',
    'container.build_time' => 1668703125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGakbhyy');
