<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ1yxjxs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ1yxjxs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ1yxjxs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ1yxjxs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ1yxjxs\appProdProjectContainer([
    'container.build_hash' => 'Z1yxjxs',
    'container.build_id' => '93ff744e',
    'container.build_time' => 1666909538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ1yxjxs');
