<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUia29nj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUia29nj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUia29nj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUia29nj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUia29nj\appProdProjectContainer([
    'container.build_hash' => 'Uia29nj',
    'container.build_id' => 'f3e36d94',
    'container.build_time' => 1668185899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUia29nj');
